django/board/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name='common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'), #LoginView -- django.contrib.auth에서 default 제공 즉 view (MVC- controller 자동 생성), registration folder 아래 login.html 찾게끔 기본 설정이 되어있음 LoginView가
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
] #URL Conf (URL 환경설정) -- URL로 어떤 것을 해야할 지 mapping 시켜 놓는 것

django/board/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('noticeboard.urls')), #board로 시작하는 것이 오면 noticeboard.urls파일을 넘길 것
    path('common/', include('common.urls'))
]

django/board/noticeboard/urls.py
from django.urls import path
from . import views

app_name='noticeboard'
urlpatterns = [
    path('', views.index, name='index'), #'' 로 들어오면 views라는 파일의 index 함수 호출, mapping index
    path('write', views.write_article, name='write_article'),
    path('add', views.add_article, name='add_article'),
    path('<int:article_id>', views.view_article, name='view'),
    path('update/<int:article_id>', views.update_article, name='update'),
    path('delete/<int:article_id>', views.delete_article, name='delete')
]

django/board/common/models.py
from django.db import models

# Create your models here.

django/board/noticeboard/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User
# Create your models here.
class Notice(models.Model): #models.Model을 상속 받음
    title=models.CharField(max_length=100)
    content=models.CharField(max_length=2000)
    write_date=models.DateTimeField(default=now, editable=False) #현재시각, 사용자가 edit 불가
    write_id=models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title #객체를 만들고 print(객체) 시 찍어줌
    

django/board/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email") #id, password, password확인, email

django/board/common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from common.forms import UserForm
# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('/board/')
    else: #post 방식이 아니면, 계정, password signup 다시 띄워줌
        form = UserForm()
    return render(request, 'registration/signup.html', {'form': form})

django/board/noticeboard/views.py
from django.shortcuts import render, redirect,get_object_or_404 #사용자에게 view를 rendering
from .models import Notice
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    article_list=Notice.objects.all().order_by('-write_date') #-: descending
    context={'article_list': article_list}
    return render(request, 'noticeboard/index.html', context) #1: request, 2: html, 3: 같이 실어줄 data

def write_article(request):
    return render(request, 'noticeboard/write_article.html')

@login_required(login_url='common:login') #common의 login으로 redirect
def add_article(request):
    notice=Notice()
    notice.title=request.POST['i_title']
    notice.content=request.POST['i_content']
    notice.write_id= request.user
    notice.save()
    
    return redirect(reverse('noticeboard:index'))

def view_article(request, article_id):
    notice=get_object_or_404(Notice, pk=article_id) #pk의 article_id있으면 넣어주고 없으면 view에 없다고 뿌려줌
    return render(request, 'noticeboard/detail.html', {'article': notice})

def update_article(request, article_id):
    notice=Notice.objects.get(id=article_id) #get한 이유는 이미 있는 것을 하니까
    
    if request.method=='POST':
        notice.title=request.POST['title']
        notice.content=request.POST['content']
        notice.write_date=timezone.datetime.now()
        notice.save()
        return redirect(reverse('noticeboard:view', args=(article_id,)))
    else:
        return render(request, 'noticeboard/detail.html', {'article': notice})
    
def delete_article(request, article_id):
    notice=Notice.objects.get(id=article_id)
    notice.delete()
    return redirect(reverse('noticeboard:index'))

django/board/templates/noticeboard/detail.html
<!DOCTYPE html>
<html lang="ko">

            <head>
                <meta charset="UTF-8">
                <title>상세 조회</title>
                <script>
                    function backToList(frm) {
                        frm.action= "{% url 'noticeboard:index' %}"
                        frm.submit();
                    }
                    function fn_enable(frm) {
                        document.querySelector('#i_title').disabled=false;
                        document.querySelector('#i_content').disabled=false;
                        document.querySelector('#tr_btn').style.display='none';
                        document.querySelector('#tr_btn_modify').style.display='table-row';
                    }
                    function fn_modify_article(frm, original_user, login_user) {
                        if(original_user != login_user) {
                            alert("사용자를 확인하세요!");
                            return false;
                        }
                        frm.action="{%url 'noticeboard:update' article.id %}";
                        frm.submit();
                    }
                    function fn_remove(frm, original_user, login_user) {
                        if(original_user != login_user) {
                            alert("사용자를 확인하세요!");
                            return false;
                        }
                        frm.action="{% url 'noticeboard:delete' article.id %}";
                        frm.submit();
                    }
                </script>
                <style>
                    #tr_btn_modify {
                        display: none;
                    }
                    
                </style>
            </head>
            <body>
                <form name="articleForm" method="post" action="">
                    {% csrf_token %}
                    <table border="0" align="center">
                        <tbody>
                            <tr>
                                <td width="150" align="center" bgcolor="#FF9933">글번호</td>
                                <td>
                                    <input type="text" value="{{article.id}}" disabled>
                                </td>
                            </tr>
                            <tr>
                                <td width="150" align="center" bgcolor="#FF9933">작성자</td>
                                <td>
                                    <input type="text" value="{{article.write_id}}" name="writer" disabled>
                                </td>
                            </tr>
                            <tr>
                                <td width="150" align="center" bgcolor="#FF9933">제목</td>
                                <td>
                                    <input type="text" value="{{article.title}}" name="title" id="i_title" disabled>
                                </td>
                            </tr>
                            <tr>
                                <td width="150" align="center" bgcolor="#FF9933">내용</td>
                                <td>
                                    <textarea rows="20" cols="60" name="content" id="i_content" disabled>{{article.content}}</textarea>
                                </td>
                            </tr>
                            <tr>
                                <td width="20%" align="center" bgcolor="#FF9933">작성일</td>
                                <td>
                                    <input type="text" value="{{article.write_date}}" disabled>
                                </td>
                            </tr>
                            <tr id="tr_btn">
                                <td colspan="2" align="center">
                                    <input type="button" value="수정" onclick="fn_enable()">
                                    <input type="button" value="삭제" 
                                    onclick="fn_remove(articleForm, '{{article.write_id}}', '{{user.username}}')">
                                    <input type="button" value="목록보기" onclick="backToList(articleForm)">
                                </td>
                            </tr>
                            <tr id="tr_btn_modify">
                                <td colspan="2" align="center">
                                    <input type="button" value ="저장" onclick="fn_modify_article(articleForm)">
                                    <input type="button" value="취소" onclick="backToList(articleForm)">
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </form>
            </body>
            </html>

django/board/templates/noticeboard/index.html
<!DOCTYPE html>
            <html lang="ko">
            <head>
                <meta charset="UTF-8">
                <title>글 목록</title>
                <style>
                    .cls1 {
                        text-decoration: none;
                    }
                    .cls2 {
                        text-align: center;
                        font-size: 30px;
                        display: block;
                    }
                </style>
            </head>
            <body>
                {% if user.is_authenticated  %} <!-- 현재 사용자가 정상적으로 인증되었는지-->
                <a class="rm_underline" href="{% url 'common:logout' %}">
                <span>{{ user.username }} (logout)</span>
                </a>
                {% else %} <!-- 정상적으로 인증되지 않은 경우-->
                <a class="rm_underline" href="{% url 'common:login' %}">
                <span>login</span>
                </a>
                {% endif %}
                <table align="center" border="1" width="80%">
                    <thead>
                        <tr height="10" align="center" bgcolor="lightgreen">
                            <th>글번호</th>
                            <th>작성자</th>
                            <th>제목</th>
                            <th>작성일</th>
                        </tr>
                    </thead>
                    {%if article_list%} <!--article_list가 있다면-->
                    <tbody>
                        {%for article in article_list%}
                        <tr align="center">
                            <td width="5%">{{forloop.counter}}</td> <!--장고에서 변수는 중괄호 2개-->
                            <td width="10%">{{article.write_id}}</td>
                            <td align="left" width="35%">
                                <span style="padding-right: 30px;"></span>
                                <a class="cls1" href="{%url 'noticeboard:view' article.id%}">
                                    {{article.title}}
                                </a>
                            </td>
                            <td width="10%">{{article.write_date}}</td>
                        </tr>
                        {%endfor%}
                    </tbody>
                    {%else%}
                    <tbody>
                        <tr height="10">
                            <td colspan="4">
                                <p align="center">
                                    <b><span style="font-size: 9pt;">등록된 글이 없습니다.</span></b>
                                </p>
                            </td>
                        </tr>
                    </tbody>
                    {%endif%}  
                </table>
                <a class="cls1" href="{%url 'noticeboard:write_article'%}"><span class="cls2">글쓰기</span></a>
            </body>
            </html>

django/board/templates/noticeboard/write_article.html
<!DOCTYPE html>
<html lang="ko">

            <head>
                <meta charset="UTF-8">
                <title>글쓰기</title>
                <script>
                    function backToList(frm) {
                        frm.action="{%url 'noticeboard:index'%}";
                        frm.submit();
                    }
                </script>
                <style>
                    .class-caption {
                        width:100px;
                    }
                    .class-content {
                        width:500px;
                    }
                </style>
            </head>

            <body>
                <h1 style="text-align: center;">글 쓰기</h1>
                <form name="articleForm" method="post" action="{% url 'noticeboard:add_article'%}">
                    {% csrf_token %} <!--쿠키에 들어가 있는 csrf_token을 꺼내서 보내줌-->
                    <table border="0" align="center">
                        <tbody>
                            <tr>
                                <td align="right" class="class-caption">글제목:</td>
                                <td colspan="2">
                                    <input {% if not user.is_authenticated %}disabled{% endif %}
                                    type="text" maxlength="100" name="i_title" class="class-content">
                                </td>
                            </tr>
                            <tr>
                                <td align="right" valign="top" class="class-caption">글내용:</td>
                                <td colspan="2">
                                    <textarea {% if not user.is_authenticated %}disabled{% endif %} 
                                    name="i_content" rows="10" maxlength="2000"
                                        class="class-content"></textarea>
                                </td>
                            </tr>
                            <tr>
                                <td align="right"></td>
                                <td colspan="2">
                                    <input {% if not user.is_authenticated %}disabled{% endif %}
                                    type="submit" value="저장">
                                    <input type="button" value="목록보기" onclick="backToList(articleForm)">
                            </tr>
                        </tbody>
                    </table>
                </form>
            </body>

            </html>